// The 25 seed extras. All details are made up.
// productions: 'wednesday', 'bloodaxe' or both.
// bank: fake Irish IBANs (they pass the checksum but aren't real accounts). null = not added yet.
// Skills/languages not in the app's lists (e.g. 'Polish') show up in the "Other" box.
module.exports = [
  // ----- The original 5 test logins (same names and productions as before) -----
  { email: 'extra1@example.com', name: 'Jordan Lee', gender: 'FEMALE', dateOfBirth: '1997-03-14', heightCm: 171,
    skills: ['Stunt work', 'Horse riding', 'Rowing'], languages: ['English'], availability: ['Everyday'],
    productions: ['wednesday'], hasSmartphone: true, bank: { iban: 'IE09BOFI90260181590830', bic: 'BOFIIE2D' } },
  { email: 'extra2@example.com', name: 'Sam Rivera', gender: 'MALE', dateOfBirth: '1992-07-02', heightCm: 180,
    skills: ['Sign language', 'Martial arts'], languages: ['English', 'Spanish'], availability: ['Mondays', 'Tuesdays', 'Wednesdays', 'Thursdays', 'Fridays'],
    productions: ['wednesday'], hasSmartphone: true, bank: { iban: 'IE83AIBK93661318609139', bic: 'AIBKIE2D' } },
  { email: 'extra3@example.com', name: 'Priya Nair', gender: 'FEMALE', dateOfBirth: '2004-01-20', heightCm: 165,
    skills: ['Dancing'], languages: ['English'], availability: ['Tuesdays', 'Thursdays'],
    productions: ['bloodaxe'], hasSmartphone: true, bank: null },
  { email: 'extra4@example.com', name: 'Chris Okafor', gender: 'MALE', dateOfBirth: '1985-06-08', heightCm: 175,
    skills: ['Stunt work', 'Boxing'], languages: ['English', 'French'], availability: ['Everyday'],
    productions: ['bloodaxe'], hasSmartphone: true, bank: { iban: 'IE41AIBK93996030824628', bic: 'AIBKIE2D' } },
  { email: 'extra5@example.com', name: 'Taylor Kim', gender: 'MALE', dateOfBirth: '1999-05-30', heightCm: 168,
    skills: ['Singing', 'Sign language', 'Stunt work'], languages: ['English'], availability: ['Mondays', 'Tuesdays', 'Wednesdays', 'Thursdays', 'Fridays'],
    productions: ['wednesday', 'bloodaxe'], hasSmartphone: true, bank: { iban: 'IE76AIBK93948219935181', bic: 'AIBKIE2D' } },

  // ----- 20 new extras -----
  { email: 'extra6@example.com', name: 'Aoife Byrne', gender: 'FEMALE', dateOfBirth: '1990-09-12', heightCm: 166,
    skills: ['Acting / improv', 'Singing'], languages: ['English', 'Irish'], availability: ['Everyday'],
    productions: ['wednesday'], hasSmartphone: true, bank: { iban: 'IE93IPBS99093786579754', bic: 'IPBSIE2D' } },
  { email: 'extra7@example.com', name: 'Liam Doyle', gender: 'MALE', dateOfBirth: '1998-02-25', heightCm: 183,
    skills: ['Stunt work', 'Horse riding', 'Martial arts', 'Archery'], languages: ['English', 'Irish'], availability: ['Everyday'],
    productions: ['bloodaxe'], hasSmartphone: true, bank: { iban: 'IE72AIBK93231948757491', bic: 'AIBKIE2D' } },
  { email: 'extra8@example.com', name: 'Seamus Walsh', gender: 'MALE', dateOfBirth: '1962-11-03', heightCm: 177,
    skills: ['Driving (manual)'], languages: ['English', 'Irish'], availability: ['Mondays', 'Wednesdays', 'Fridays'],
    productions: ['wednesday', 'bloodaxe'], hasSmartphone: false, bank: { iban: 'IE24AIBK93862527601895', bic: 'AIBKIE2D' } },
  { email: 'extra9@example.com', name: 'Niamh Kelly', gender: 'FEMALE', dateOfBirth: '2003-06-18', heightCm: 162,
    skills: ['Dancing', 'Gymnastics / yoga'], languages: ['English', 'French'], availability: ['Everyday'],
    productions: ['wednesday'], hasSmartphone: true, bank: null },
  { email: 'extra10@example.com', name: 'Ciara Murphy', gender: 'FEMALE', dateOfBirth: '1980-04-07', heightCm: 169,
    skills: ['Horse riding', 'Swimming'], languages: ['English', 'Irish'], availability: ['Tuesdays', 'Wednesdays', 'Thursdays'],
    productions: ['bloodaxe'], hasSmartphone: true, bank: { iban: 'IE87BOFI90597971147104', bic: 'BOFIIE2D' } },
  { email: 'extra11@example.com', name: 'Darragh Nolan', gender: 'MALE', dateOfBirth: '2006-08-22', heightCm: 185,
    skills: ['Boxing', 'Cycling'], languages: ['English'], availability: ['Everyday'],
    productions: ['bloodaxe'], hasSmartphone: true, bank: null },
  { email: 'extra12@example.com', name: 'Grace Okafor', gender: 'FEMALE', dateOfBirth: '1995-12-01', heightCm: 172,
    skills: ['Acting / improv', 'Musical instrument'], languages: ['English'], availability: ['Mondays', 'Tuesdays', 'Wednesdays', 'Thursdays', 'Fridays'],
    productions: ['wednesday'], hasSmartphone: true, bank: { iban: 'IE33IPBS99974650752917', bic: 'IPBSIE2D' } },
  { email: 'extra13@example.com', name: 'Tomasz Nowak', gender: 'MALE', dateOfBirth: '1984-03-29', heightCm: 188,
    skills: ['Stunt work', 'Firearms (licensed)'], languages: ['English', 'German', 'Polish'], availability: ['Everyday'],
    productions: ['wednesday', 'bloodaxe'], hasSmartphone: true, bank: { iban: 'IE89AIBK93342366712768', bic: 'AIBKIE2D' } },
  { email: 'extra14@example.com', name: 'Freya Lindqvist', gender: 'FEMALE', dateOfBirth: '1993-07-15', heightCm: 176,
    skills: ['Horse riding', 'Rowing', 'Archery'], languages: ['English', 'Swedish', 'Norwegian'], availability: ['Everyday'],
    productions: ['bloodaxe'], hasSmartphone: true, bank: { iban: 'IE33BOFI90268465632122', bic: 'BOFIIE2D' } },
  { email: 'extra15@example.com', name: 'Eoin Gallagher', gender: 'MALE', dateOfBirth: '1976-10-10', heightCm: 179,
    skills: ['Driving (manual)', 'Motorbike'], languages: ['English'], availability: ['Mondays', 'Tuesdays'],
    productions: ['wednesday', 'bloodaxe'], hasSmartphone: true, bank: { iban: 'IE28AIBK93307924402685', bic: 'AIBKIE2D' } },
  { email: 'extra16@example.com', name: 'Maeve Brennan', gender: 'FEMALE', dateOfBirth: '1958-01-26', heightCm: 160,
    skills: ['Singing'], languages: ['English', 'Irish'], availability: ['Wednesdays', 'Thursdays'],
    productions: ['wednesday'], hasSmartphone: false, bank: null },
  { email: 'extra17@example.com', name: 'Oisín Fitzgerald', gender: 'MALE', dateOfBirth: '2001-05-05', heightCm: 181,
    skills: ['Martial arts', 'Gymnastics / yoga', 'Archery'], languages: ['English', 'Irish'], availability: ['Everyday'],
    productions: ['bloodaxe'], hasSmartphone: true, bank: null },
  { email: 'extra18@example.com', name: 'Sofia Costa', gender: 'FEMALE', dateOfBirth: '1996-11-19', heightCm: 164,
    skills: ['Dancing', 'Swimming'], languages: ['English', 'Portuguese', 'Spanish'], availability: ['Mondays', 'Tuesdays', 'Wednesdays', 'Thursdays', 'Fridays'],
    productions: ['wednesday'], hasSmartphone: true, bank: { iban: 'IE76IPBS99952890786666', bic: 'IPBSIE2D' } },
  { email: 'extra19@example.com', name: 'Bjorn Halvorsen', gender: 'MALE', dateOfBirth: '1988-02-14', heightCm: 191,
    skills: ['Stunt work', 'Rowing', 'Horse riding', 'Archery'], languages: ['English', 'Norwegian', 'Icelandic'], availability: ['Everyday'],
    productions: ['bloodaxe'], hasSmartphone: true, bank: { iban: 'IE69AIBK93760313721590', bic: 'AIBKIE2D' } },
  { email: 'extra20@example.com', name: 'Róisín Keane', gender: 'FEMALE', dateOfBirth: '1971-08-30', heightCm: 167,
    skills: ['Musical instrument'], languages: ['English', 'Irish'], availability: ['Tuesdays', 'Fridays'],
    productions: ['wednesday'], hasSmartphone: false, bank: null },
  { email: 'extra21@example.com', name: 'Patrick Moran', gender: 'MALE', dateOfBirth: '1955-06-12', heightCm: 174,
    skills: ['Driving (manual)'], languages: ['English'], availability: ['Everyday'],
    productions: ['wednesday', 'bloodaxe'], hasSmartphone: false, bank: { iban: 'IE73AIBK93092815901396', bic: 'AIBKIE2D' } },
  { email: 'extra22@example.com', name: 'Hannah Dunne', gender: 'FEMALE', dateOfBirth: '2005-03-03', heightCm: 170,
    skills: ['Gymnastics / yoga', 'Cycling'], languages: ['English'], availability: ['Everyday'],
    productions: ['bloodaxe'], hasSmartphone: true, bank: null },
  { email: 'extra23@example.com', name: "Kevin O'Brien", gender: 'MALE', dateOfBirth: '1990-12-24', heightCm: 178,
    skills: ['Boxing', 'Swimming'], languages: ['English'], availability: ['Mondays', 'Wednesdays', 'Fridays'],
    productions: ['wednesday'], hasSmartphone: true, bank: { iban: 'IE80AIBK93459571177774', bic: 'AIBKIE2D' } },
  { email: 'extra24@example.com', name: 'Astrid Jensen', gender: 'FEMALE', dateOfBirth: '1987-09-09', heightCm: 173,
    skills: ['Rowing', 'Swimming', 'Archery'], languages: ['English', 'Danish', 'Dutch'], availability: ['Everyday'],
    productions: ['bloodaxe'], hasSmartphone: true, bank: null },
  { email: 'extra25@example.com', name: 'Mark Tierney', gender: 'MALE', dateOfBirth: '1968-04-16', heightCm: 182,
    skills: ['Firearms (licensed)', 'Driving (manual)'], languages: ['English'], availability: ['Thursdays', 'Fridays'],
    productions: ['wednesday'], hasSmartphone: false, bank: { iban: 'IE89AIBK93215472803852', bic: 'AIBKIE2D' } },
];